program: GabatinoTaylor08.o getdouble.o
	gcc GabatinoTaylor08.o getdouble.o -o program -lm

GabatinoTaylor08.o: GabatinoTaylor08.c getdouble.h
	gcc -c GabatinoTaylor08.c

getdouble.o: getdouble.c getdouble.h
	gcc -c getdouble.c

